apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zb1lhakjk-nodejs 
  janus-idp.io/tekton: zb1lhakjk-nodejs
  backstage.io/kubernetes-id: zb1lhakjk-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zb1lhakjk-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  