apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zb1lhakjk-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zb1lhakjk-nodejs 
  name: zb1lhakjk-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: zb1lhakjk-nodejs 
